const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch({ headless: true });
  const context = await browser.newContext({ ignoreHTTPSErrors: true });
  const page = await context.newPage();

  console.log("Navigating to login page...");
  await page.goto('https://panel.yunusaydin.av.tr/wp-login.php');

  console.log("Filling credentials...");
  await page.fill('#user_login', 'admin');
  await page.fill('#user_pass', 'TPY$b%$4PK');
  await page.click('#wp-submit');
  
  await page.waitForLoadState('networkidle');
  console.log("Logged in!");

  // --- Ana Sayfa (ID: 10) ---
  console.log("Updating Ana Sayfa texts...");
  await page.goto('https://panel.yunusaydin.av.tr/wp-admin/post.php?post=10&action=edit');
  try {
    await page.waitForSelector('.acf-field', { timeout: 15000 });

    // Update by finding the label text since we don't know the exact ACF field keys generated by WP
    
    // Ana Slogan
    const sloganField = page.locator('.acf-field:has-text("Ana Slogan") input[type="text"]').first();
    await sloganField.fill('GÜVENİLİR HUKUKİ ÇÖZÜMLER');

    // Ana Başlık
    const baslikField = page.locator('.acf-field:has-text("Ana Baslik") input[type="text"], .acf-field:has-text("Ana Başlık") input[type="text"]').first();
    await baslikField.fill('Haklarınızın Güçlü Savunucusu');

    // Hakkımda Özeti
    const ozetField = page.locator('.acf-field:has-text("Hakkimda Ozeti") textarea, .acf-field:has-text("Hakkımda Özeti") textarea').first();
    await ozetField.fill('Avukat Yunus Aydın, hukuki uyuşmazlıklarda profesyonel, şeffaf ve sonuç odaklı danışmanlık ve avukatlık hizmetleri sunmaktadır. Haklarınızı korumak ve size en iyi hukuki desteği sağlamak önceliğimizdir.');

    console.log("Fields filled, saving...");
    await page.evaluate(() => {
      const btn = document.querySelector('.editor-post-publish-button');
      if (btn) btn.click();
    });
    await page.waitForTimeout(3000);
    console.log("Ana Sayfa updated successfully!");
  } catch (e) {
    console.log("Error updating Ana Sayfa:", e.message);
  }

  await browser.close();
})();
